name: Daily CSV Update

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-csv:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install express node-fetch@2 cors fs node-cron
      
    - name: Run CSV update script
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'
        PORT: '3000'
      run: |
        # Start the server in the background
        node server.js &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Call the save-csv endpoint
        curl -X GET http://localhost:3000/save-csv
        
        # Kill the server
        kill $SERVER_PID
        
        # Wait for server to shut down
        sleep 2
      
    - name: Commit and push if changed
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git status
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update dependencies and CSV data [skip ci]" && git push) 